Fix wrong import from six.moves to make openstackwatch workable
The method urlretrieve is part of urllib.request and not urllib.parse.

six.moves.urllib.request has to be used instead of six.moves.urllib.parse to
be able to use urlretrieve in the method get_javascript.

This solves the follwoing issue when running openstackwatch.

---snip---
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlretrieve'
---snap---

Change-Id: I95d73b3d5b01bd7097295ba524e44954b7d284a5